name: Deploy PBI configuration
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      environment:
        type: choice
        description: which environment to deploy
        required: true
        options:
        - dev
        - prod
        
defaults:
  run:
    working-directory: ./scripts/

env:
  TF_BACKEND_CONFIG: >-
    -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
    
permissions:
      id-token: write
      contents: read

jobs:
  log-in-azure:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it     
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: 
          ./configure-pb1.ps1
        shell: pwsh
